// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreAnimation;
using UIKit;

namespace MatchedBetMate.iOS
{
    public partial class ValidatedTextField : UITextField
	{
        private CALayer _border;

        public bool Valid
        {
            set
            {
                if (value)
                {
                    _border.BorderColor = UIColor.Green.CGColor;
                }
                else
                {
                    _border.BorderColor = UIColor.Red.CGColor;
                }
            }
        }

		public ValidatedTextField (IntPtr handle) : base (handle)
		{
            CreateBorder();
		}

        private void CreateBorder()
        {
            _border = new CALayer();
            var width = (float)2.0;
            _border.Frame = new CoreGraphics.CGRect(0, this.Frame.Size.Height - width, this.Frame.Size.Width, this.Frame.Size.Height);
            _border.BorderWidth = width;
            _border.BorderColor = UIColor.Clear.CGColor;
            this.Layer.AddSublayer(_border);
            this.Layer.MasksToBounds = true;
        }
	}
}
