// This file has been autogenerated from a class added in the UI designer.

using System;
using UIKit;

namespace MatchedBetMate.iOS.ViewControllers
{
	public partial class CreateAccountViewController : UIViewController
	{
		public CreateAccountViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
