// This file has been autogenerated from a class added in the UI designer.

using System;
using MatchedBetMate.iOS.ViewControllers.Base;
using MatchedBetMate.iOS.ViewModels;
using UIKit;

namespace MatchedBetMate.iOS.ViewControllers
{
	public partial class LoginViewController : BaseViewController<LoginViewModel>
	{
		public LoginViewController (IntPtr handle) : base (handle, new LoginViewModel())
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            ConfigureGestureRecognisers();
            ConfigureTextInputEvents();

        }

	    async partial void LoginButton_TouchUpInside(Foundation.NSObject sender)
        {
            await ViewModel.Login(EmailAddressInput.Text, PasswordInput.Text);

            NavigateToHomePage();
        }

        private void ConfigureTextInputEvents()
        {
            EmailAddressInput.EditingChanged += (sender, e) => HandleEmailInputUi();
        }

        private void HandleEmailInputUi()
        {
            // TODO Helper method to validate email against regex
            var validEmail = EmailAddressInput.Text.Length > 5;
            EmailAddressInput.Valid = validEmail;
        }

        private void ConfigureGestureRecognisers()
        {
            var tapGesture = new UITapGestureRecognizer(NavigateToCreateAccount);
            CreateNewAccountLabel.AddGestureRecognizer(tapGesture);
        }

        private void NavigateToHomePage()
        {
            var mainStoryBoard = UIStoryboard.FromName("Main", null);

            if (mainStoryBoard != null)
            {
                var vc = mainStoryBoard.InstantiateInitialViewController();
                if (vc != null)
                {
                    PresentViewController(vc, true, null);
                }
            }
        }

        private void NavigateToCreateAccount()
        {
            PerformSegue("CreateAccount", this);
        }
	}
}
